# Generated by Django 4.2.1 on 2023-05-19 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('createddt', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 16, 10, 32, 138788, tzinfo=datetime.timezone.utc))),
                ('event', models.CharField(max_length=500)),
                ('ondate', models.DateField()),
                ('ontime', models.TimeField()),
            ],
            options={
                'db_table': 'ToDo',
            },
        ),
    ]
