# Generated by Django 4.2.1 on 2023-05-19 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='createddt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 22, 3, 32, 441109)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='ondate',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='ontime',
            field=models.TimeField(verbose_name='Time'),
        ),
    ]
