# Generated by Django 4.2.1 on 2023-05-20 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_todomodel_createddt_alter_todomodel_ondate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='createddt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 15, 44, 19, 560105)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='ontime',
            field=models.TimeField(blank=True, verbose_name='Time'),
        ),
    ]
