# Generated by Django 4.2.1 on 2023-05-20 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_todomodel_createddt_alter_todomodel_ontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='createddt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 15, 51, 42, 143178)),
        ),
    ]
