# Generated by Django 4.2.1 on 2023-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_todomodel_createddt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='createddt',
            field=models.DateTimeField(null=True),
        ),
    ]
