# Generated by Django 4.2.1 on 2023-05-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_todomodel_createddt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='ondate',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='ontime',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='dt',
            field=models.DateTimeField(null=True),
        ),
    ]
