# Generated by Django 4.2.1 on 2023-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_todomodel_ondate_remove_todomodel_ontime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='dt',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
    ]
